#Deploy do MongoDB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongobd
spec:
  selector:
    matchLabels:
      app: mongobd
  template:
    metadata:
      labels:
        app: mongobd
    spec:
      containers:
        - name: mongobd
          image: mongo:5.0.5
          ports:
            - containerPort: 27017
          env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: mongouser
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: mongopwd

---
apiVersion: v1
kind: Service
metadata:
  name: mongobd
spec:
  selector:
    app: mongobd
  ports:
  - port: 27017
  type: ClusterIP

---

# Deploy da aplicação rotten potatoes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webrotten
spec:
  selector:
    matchLabels:
      app: webrotten
  template:
    metadata:
      labels:
        app: webrotten
    spec:
      containers:
      - name: webrotten
        image: flvasques/rotten-potatoes:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_DB
          value: admin
        - name: MONGODB_HOST
          value: mongobd
        - name: MONGODB_PORT
          value: "27017"
        - name: MONGODB_USERNAME
          value: mongouser
        - name: MONGODB_PASSWORD
          value: mongopwd

---
apiVersion: v1
kind: Service
metadata:
  name: webrotten
spec:
  selector:
    app: webrotten
  ports:
  - port: 80
    targetPort: 5000
    nodePort: 30000
  type: LoadBalancer

